Repository WikiWatershed/model-my-watershed, pull requests merged in 2018-02, with the labels that each got.

#2659 Analysis & Model Reorders
  src/mmw/js/src/analyze/models.js
  src/mmw/js/src/modeling/gwlfe/quality/templates/table.html
  src/mmw/sass/components/_tabs.scss
Labels: in progress

#2658 Mandatorily Make Projects Public After HydroShare Export
  src/mmw/apps/export/views.py
  src/mmw/js/src/core/modals/templates/multiShareModal.html
  src/mmw/js/src/modeling/models.js
Labels: HydroShare Export, in progress

#2661 Allow Opening MMW Project via HydroShare Resource ID
  src/mmw/apps/home/urls.py
  src/mmw/apps/home/views.py
Labels: HydroShare Export, in progress

#2664 HydroShare Export: Allow Open With Behavior
  src/mmw/apps/export/views.py
Labels: HydroShare Export, in progress

#2665 Updates to Splash and Header text
  src/mmw/img/logo-wikiwatershed-white.png
  src/mmw/js/src/core/templates/header.html
  src/mmw/js/src/core/views.js
  src/mmw/js/src/draw/settings.js
  src/mmw/js/src/draw/templates/splash.html
  src/mmw/js/src/draw/views.js
Labels: in progress

#2663 Monitor: Add BiG-CZ Search
  src/mmw/js/src/analyze/templates/resultsWindow.html
  src/mmw/js/src/analyze/views.js
  src/mmw/js/src/app.js
  src/mmw/js/src/core/models.js
  src/mmw/js/src/core/views.js
  src/mmw/js/src/data_catalog/templates/filterSidebar.html
  src/mmw/js/src/data_catalog/templates/form.html
  src/mmw/js/src/data_catalog/templates/pager.html
  src/mmw/js/src/data_catalog/templates/resultDetailsCuahsi.html
  src/mmw/js/src/data_catalog/templates/window.html
  src/mmw/js/src/data_catalog/views.js
  src/mmw/js/src/draw/views.js
  src/mmw/js/src/modeling/controllers.js
  src/mmw/js/src/monitor/templates/window.html
  src/mmw/js/src/monitor/views.js
  src/mmw/js/src/projects/views.js
  src/mmw/sass/components/_buttons.scss
  src/mmw/sass/components/_tabs.scss
  src/mmw/sass/main.scss
  src/mmw/sass/pages/_data-catalog.scss
  src/mmw/sass/pages/_monitor.scss
Labels: Monitor, in progress

#2672 Harmonize Downloadable Analyze CSV Names With API and Hydroshare
  src/mmw/js/src/analyze/views.js
Labels: in progress

#2675 Monitor: Modeling Stage Interaction
  src/mmw/js/src/analyze/views.js
  src/mmw/js/src/app.js
  src/mmw/js/src/core/utils.js
  src/mmw/js/src/data_catalog/controllers.js
  src/mmw/js/src/data_catalog/views.js
  src/mmw/js/src/draw/views.js
  src/mmw/js/src/modeling/controllers.js
  src/mmw/js/src/modeling/models.js
  src/mmw/js/src/modeling/templates/projectMenu.html
  src/mmw/js/src/modeling/templates/resultsWindow.html
  src/mmw/js/src/modeling/views.js
  src/mmw/js/src/projects/views.js
  src/mmw/sass/components/_tabs.scss
  src/mmw/sass/pages/_analyze.scss
  src/mmw/sass/pages/_data-catalog.scss
Labels: in progress

#2674 Don't show "Add changes" if project was not created by current user
  src/mmw/js/src/compare/views.js
  src/mmw/js/src/core/templates/modificationPopup.html
  src/mmw/js/src/core/tests.js
  src/mmw/js/src/core/views.js
  src/mmw/js/src/modeling/controllers.js
  src/mmw/js/src/modeling/templates/gwlfeScenarioToolbar.html
  src/mmw/js/src/modeling/templates/scenarioAddChangesButton.html
  src/mmw/js/src/modeling/views.js
Labels: in progress

#2685 Show drawn modifications only in Modeling tab
  src/mmw/js/src/modeling/views.js
Labels: Monitor, in progress

#2686 Adjust bar chart ticks on tab switch
  src/mmw/js/src/analyze/views.js
Labels: in progress
