Repository WikiWatershed/model-my-watershed, pull requests merged in 2018-06, with the labels that each got.

#2858 Subbasin: Fine Tune Catchment Coloring
  src/mmw/js/src/core/views.js
  src/mmw/js/src/modeling/gwlfe/subbasin/models.js
  src/mmw/js/src/modeling/models.js
Labels: NSF, Sub-basin Modeling

#2868 Subbasin: Layer Legend and Opacity
  src/mmw/apps/home/templates/home/home.html
  src/mmw/js/src/core/models.js
  src/mmw/js/src/core/views.js
  src/mmw/js/src/modeling/gwlfe/subbasin/models.js
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/layerLegend.html
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/layerSelector.html
  src/mmw/js/src/modeling/gwlfe/subbasin/views.js
  src/mmw/js/src/modeling/models.js
  src/mmw/sass/pages/_model.scss
Labels: Sub-basin Modeling

#2866 Monitor: Limit CUAHSI /values/ to 5s
  deployment/ansible/roles/model-my-watershed.app/templates/gunicorn.py.j2
  src/mmw/apps/bigcz/clients/cuahsi/details.py
  src/mmw/apps/bigcz/utils.py
  src/mmw/js/src/data_catalog/models.js
  src/mmw/requirements/base.txt
Labels: Monitor

#2870 Monitor: Fix CINERGI
  src/mmw/apps/bigcz/clients/cinergi/search.py
  src/mmw/apps/bigcz/utils.py
  src/mmw/mmw/settings/base.py
Labels: Monitor

#2872 Monitor: Fix Contribute Links
  src/mmw/js/src/data_catalog/templates/contributeModal.html
Labels: in progress

#2876 Adjust SedAAdjust to 1.5
  src/mmw/apps/modeling/mapshed/tasks.py
  src/mmw/mmw/settings/gwlfe_settings.py
Labels: in progress

#2877 Add Shippensburg Future Land Use layers
  src/mmw/mmw/settings/layer_settings.py
  src/mmw/sass/components/_layerpicker.scss
Labels: in progress

#2878 Change soiln adjustment factor to 9.0
  src/mmw/apps/modeling/mapshed/tasks.py
Labels: in progress

#2879 Combine PA Municipalities with Urbanization Layer
  src/mmw/js/src/core/layerPicker.js
  src/mmw/js/src/core/models.js
  src/mmw/js/src/core/utils.js
  src/mmw/mmw/settings/layer_settings.py
  src/mmw/sass/components/_layerpicker.scss
  src/tiler/styles.mss
Labels: in progress
