Repository WikiWatershed/model-my-watershed, pull requests merged in 2018-11, with the labels that each got.

#3018 Upgrade GWLF-E to 2.0.0
  src/mmw/requirements/base.txt
Labels: in progress

#3017 Update Logo, Favicon
  src/mmw/apps/home/static/favicon.png
  src/mmw/apps/home/static/favicon@2x.png
  src/mmw/img/logo-mmw-white.png
  src/mmw/js/src/core/templates/header.html
Labels: NSF, in progress

#3020 Unit Conversion: Draw and Analyze
  src/mmw/js/src/analyze/templates/catchmentWaterQualityTable.html
  src/mmw/js/src/analyze/templates/catchmentWaterQualityTableRow.html
  src/mmw/js/src/analyze/templates/climateTable.html
  src/mmw/js/src/analyze/templates/pointSourceTable.html
  src/mmw/js/src/analyze/templates/pointSourceTableRow.html
  src/mmw/js/src/analyze/templates/streamLengthPopover.html
  src/mmw/js/src/analyze/templates/streamTable.html
  src/mmw/js/src/analyze/templates/streamTableRow.html
  src/mmw/js/src/analyze/templates/terrainTable.html
  src/mmw/js/src/analyze/tests.js
  src/mmw/js/src/analyze/views.js
  src/mmw/js/src/core/catchmentWaterQualityLayer.js
  src/mmw/js/src/core/models.js
  src/mmw/js/src/core/pointSourceLayer.js
  src/mmw/js/src/core/templates/catchmentWaterQualityPopup.html
  src/mmw/js/src/core/templates/pointSourcePopup.html
  src/mmw/js/src/core/tests.js
  src/mmw/js/src/core/units.js
  src/mmw/js/src/core/utils.js
  src/mmw/js/src/draw/utils.js
  src/mmw/js/src/draw/views.js
  src/mmw/js/src/modeling/mocks.js
  src/mmw/js/src/modeling/tests.js
  src/mmw/mmw/settings/base.py
  src/mmw/mmw/settings/gwlfe_settings.py
Labels: NSF, Unit Conversion, in progress

#3021 Pin version of Python Redis module to 2.x series
  src/mmw/requirements/base.txt
Labels: in progress

#3030 Unit Conversion: TR-55
  src/mmw/js/src/compare/constants.js
  src/mmw/js/src/compare/models.js
  src/mmw/js/src/compare/tests.js
  src/mmw/js/src/compare/views.js
  src/mmw/js/src/core/units.js
  src/mmw/js/src/core/utils.js
  src/mmw/js/src/modeling/controls.js
  src/mmw/js/src/modeling/mocks.js
  src/mmw/js/src/modeling/templates/controls/precipitation.html
  src/mmw/js/src/modeling/tr55/models.js
  src/mmw/js/src/modeling/tr55/quality/templates/chart.html
  src/mmw/js/src/modeling/tr55/quality/templates/table.html
  src/mmw/js/src/modeling/tr55/quality/views.js
  src/mmw/js/src/modeling/tr55/runoff/templates/table.html
  src/mmw/js/src/modeling/tr55/runoff/views.js
Labels: NSF, Unit Conversion, in progress

#3029 Enable client side filtering for WQP catalog
  src/mmw/apps/bigcz/clients/usgswqp/search.py
  src/mmw/js/src/data_catalog/models.js
Labels: Monitor, NSF, in progress

#3033 Unit Conversion: MapShed
  src/mmw/js/src/compare/constants.js
  src/mmw/js/src/compare/models.js
  src/mmw/js/src/compare/utils.js
  src/mmw/js/src/compare/views.js
  src/mmw/js/src/core/filters.js
  src/mmw/js/src/core/units.js
  src/mmw/js/src/modeling/controls.js
  src/mmw/js/src/modeling/gwlfe/entry/templates/landCoverTotal.html
  src/mmw/js/src/modeling/gwlfe/entry/views.js
  src/mmw/js/src/modeling/gwlfe/quality/templates/table.html
  src/mmw/js/src/modeling/gwlfe/quality/views.js
  src/mmw/js/src/modeling/gwlfe/runoff/templates/result.html
  src/mmw/js/src/modeling/gwlfe/runoff/templates/table.html
  src/mmw/js/src/modeling/gwlfe/runoff/views.js
  src/mmw/js/src/modeling/gwlfeModificationConfig.js
  src/mmw/js/src/modeling/templates/controls/manualEntry.html
  src/mmw/js/src/modeling/templates/gwlfeScenarioToolbar.html
  src/mmw/js/src/modeling/views.js
Labels: NSF, Unit Conversion, in progress

#3032 HydroShare Bulk Upload
  src/mmw/apps/export/hydroshare.py
  src/mmw/apps/export/tasks.py
Labels: HydroShare Export, in progress

#3035 Unit Conversion: Subbasin
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/catchmentTable.html
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/huc12TotalsTable.html
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/sourcesTable.html
  src/mmw/js/src/modeling/gwlfe/subbasin/views.js
Labels: in progress
