Repository WikiWatershed/model-my-watershed, pull requests merged in 2018-03, with the labels that each got.

#2691 Fix Re-Opening Modification Dropdown
  src/mmw/js/src/modeling/controls.js
Labels: in progress

#2693 Monitor Search Fixes
  src/mmw/apps/bigcz/clients/cuahsi/search.py
  src/mmw/apps/bigcz/models.py
  src/mmw/js/src/data_catalog/models.js
  src/mmw/js/src/data_catalog/views.js
Labels: Monitor, in progress

#2694 Update libpq glob to reflect main PostgreSQL repository
  deployment/ansible/group_vars/all
Labels: in review

#2698 Fix hydroshare resource link in safari
  src/mmw/js/src/core/modals/templates/multiShareModal.html
Labels: in progress

#2705 Clear analysis results on selecting geocoder shape
  src/mmw/js/src/geocode/views.js
Labels: in progress

#2696 Add elevation layer to layerpicker
  src/mmw/apps/geoprocessing_api/tasks.py
  src/mmw/js/src/analyze/views.js
  src/mmw/mmw/settings/base.py
  src/mmw/mmw/settings/layer_settings.py
  src/mmw/sass/components/_layerpicker.scss
Labels: in progress

#2704 Monitor: Remove Search Data Button in BiG-CZ
  src/mmw/js/src/analyze/templates/dataSourceButton.html
  src/mmw/js/src/analyze/templates/resultsWindow.html
  src/mmw/js/src/analyze/views.js
  src/mmw/js/src/data_catalog/controllers.js
  src/mmw/js/src/routes.js
  src/mmw/sass/components/_buttons.scss
  src/mmw/sass/pages/_analyze.scss
Labels: BigCZ, Monitor, in progress

#2701 Pre-release UI Cleanup
  src/mmw/js/src/analyze/templates/aoiHeader.html
  src/mmw/sass/pages/_analyze.scss
Labels: in progress

#2700 HydroShare Export: Properly Include Model Results as CSV
  src/mmw/js/src/core/utils.js
  src/mmw/js/src/modeling/models.js
  src/mmw/js/src/modeling/templates/projectMenu.html
Labels: HydroShare Export, in progress

#2710 Monitor: Throttle EnviroDIY values to 2 weeks
  src/mmw/js/src/data_catalog/models.js
Labels: Monitor, in progress

#2712 Account for origin/ prefix in branch names
  src/mmw/js/src/core/tests.js
  src/mmw/js/src/core/utils.js
Labels: in progress

#2725 Fix HydroShare Login in Internet Explorer
  src/mmw/apps/user/templates/user/hydroshare-auth.html
  src/mmw/js/src/account/views.js
  src/mmw/js/src/core/modals/views.js
  src/mmw/js/src/core/utils.js
Labels: in progress
