Repository WikiWatershed/model-my-watershed, pull requests merged in 2018-07, with the labels that each got.

#2887 Monitor: Add WQP, Anonymize IP Addresses
  src/mmw/apps/core/templates/head.html
  src/mmw/js/src/data_catalog/models.js
Labels: Monitor, in progress

#2888 Add Mid-Atlantic ARA layer
  src/mmw/mmw/settings/layer_settings.py
Labels: in progress

#2892 Add DRB Urban Land Cover 2011 tile layer to app
  src/mmw/mmw/settings/layer_settings.py
  src/mmw/sass/components/_layerpicker.scss
Labels: in progress

#2896 Add Marker for Coordinate, Address Search
  src/mmw/js/src/core/models.js
  src/mmw/js/src/core/views.js
  src/mmw/js/src/draw/controllers.js
  src/mmw/js/src/geocode/models.js
Labels: NSF, in progress
