Repository WikiWatershed/model-my-watershed, pull requests merged in 2018-04, with the labels that each got.

#2737 Use New MultiOperation for MapShed and Sub-basin
  deployment/ansible/group_vars/all
  src/mmw/apps/modeling/calcs.py
  src/mmw/apps/modeling/geoprocessing.py
  src/mmw/apps/modeling/mapshed/calcs.py
  src/mmw/apps/modeling/mapshed/tasks.py
  src/mmw/apps/modeling/views.py
  src/mmw/mmw/settings/base.py
Labels: MapShed, Sub-basin Modeling

#2740 Format SRAT Response Sub-basin
  src/mmw/apps/modeling/tasks.py
  src/mmw/apps/modeling/views.py
Labels: in progress

#2752 Configure Workers With SRAT Catchment API Env Vars
  deployment/cfn/worker.py
Labels: in progress

#2751 Add Geoprocessing Request Timeout
  src/mmw/apps/modeling/geoprocessing.py
  src/mmw/apps/modeling/tasks.py
  src/mmw/mmw/settings/base.py
Labels: in review

#2757 Fix Geocoder Behaviour When Sidebar Is Collapsed
  src/mmw/js/src/core/sidebarToggleControl.js
  src/mmw/js/src/core/views.js
Labels: in progress

#2744 Display subbasin results view via water quality tab link
  src/mmw/js/src/modeling/gwlfe/quality/templates/result.html
  src/mmw/js/src/modeling/gwlfe/quality/views.js
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/result.html
  src/mmw/js/src/modeling/gwlfe/subbasin/views.js
  src/mmw/js/src/modeling/models.js
  src/mmw/js/src/modeling/templates/resultsDetails.html
  src/mmw/js/src/modeling/views.js
  src/mmw/sass/pages/_model.scss
Labels: in progress

#2768 Use Boto to identify most recent Ubuntu release AMI
  deployment/packer/driver.py
Labels: in progress

#2770 Chunk Subbasin Gwlfe Tasks
  src/mmw/apps/core/tasks.py
  src/mmw/apps/modeling/calcs.py
  src/mmw/apps/modeling/tasks.py
  src/mmw/apps/modeling/views.py
Labels: in progress

#2773 Update MapShed Weather Station EtAdj Values
  scripts/aws/setupdb.sh
Labels: in progress

#2772 Add Subbasin Container; Refactor Result Models
  scripts/toggle_feature.sh
  src/mmw/js/src/modeling/gwlfe/subbasin/models.js
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/huc12TotalsTable.html
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/result.html
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/sourcesTable.html
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/tableTabContent.html
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/tableTabPanel.html
  src/mmw/js/src/modeling/gwlfe/subbasin/views.js
  src/mmw/js/src/modeling/models.js
  src/mmw/js/src/modeling/templates/subbasinResultsTabContent.html
  src/mmw/js/src/modeling/views.js
Labels: in progress

#2777 Sub-basin: Add AOI-Level Source Table
  src/mmw/apps/modeling/tasks.py
  src/mmw/apps/modeling/views.py
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/sourcesTable.html
  src/mmw/js/src/modeling/gwlfe/subbasin/views.js
  src/mmw/mmw/settings/base.py
  src/mmw/mmw/settings/gwlfe_settings.py
  src/mmw/sass/components/_tables.scss
  src/mmw/sass/components/_tabs.scss
Labels: in progress

#2780 Add Subbasin HUC-12 Totals Table
  src/mmw/apps/modeling/calcs.py
  src/mmw/apps/modeling/tasks.py
  src/mmw/apps/modeling/urls.py
  src/mmw/apps/modeling/views.py
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/huc12TotalsTable.html
  src/mmw/js/src/modeling/gwlfe/subbasin/views.js
  src/mmw/js/src/modeling/models.js
Labels: in progress

#2779 Upgrade GWLF-E Package
  src/mmw/requirements/base.txt
Labels: in progress

#2781 Add HUC-12 Level Subbasin View
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/huc12TotalsTable.html
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/sourcesTable.html
  src/mmw/js/src/modeling/gwlfe/subbasin/views.js
  src/mmw/js/src/modeling/templates/resultsDetails.html
  src/mmw/js/src/modeling/templates/subbasinResultsTabContent.html
  src/mmw/js/src/modeling/views.js
  src/mmw/sass/components/_tables.scss
  src/mmw/sass/pages/_model.scss
Labels: in progress

#2785 Add EnviroDIY source data link
  src/mmw/apps/bigcz/clients/cuahsi/search.py
Labels: Monitor, in progress

#2784 Monitor: Increase Area of Interest Limit with suds-jurko
  deployment/ansible/roles/model-my-watershed.app/tasks/dependencies.yml
  src/mmw/apps/bigcz/clients/cuahsi/search.py
  src/mmw/js/src/data_catalog/models.js
  src/mmw/mmw/settings/base.py
  src/mmw/requirements/base.txt
Labels: Monitor, in progress

#2786 Show Subbasin Huc-12s On Map
  src/mmw/js/src/core/views.js
  src/mmw/js/src/modeling/controllers.js
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/huc12TotalsTable.html
  src/mmw/js/src/modeling/gwlfe/subbasin/views.js
  src/mmw/js/src/modeling/models.js
  src/mmw/js/src/modeling/views.js
  src/mmw/sass/components/_tables.scss
Labels: in progress

#2790 Allow MapShed to run for AoIs without streams
  src/mmw/apps/modeling/geoprocessing.py
  src/mmw/apps/modeling/mapshed/tasks.py
Labels: in progress

#2792 Close sub-basin view when changing scenarios
  src/mmw/js/src/modeling/views.js
Labels: Sub-basin Modeling, in progress

#2795 Upgrade Omgeo to correctly resolve suds-jurko
  deployment/ansible/roles/model-my-watershed.app/tasks/dependencies.yml
  src/mmw/mmw/settings/base.py
  src/mmw/requirements/base.txt
Labels: in progress

#2793 Upgrade Docker to resolve key issues
  deployment/ansible/roles.yml
Labels: in progress

#2788 Clear old MapShed results
  src/mmw/apps/modeling/migrations/0028_clear_old_mapshed_results.py
Labels: MapShed, in progress

#2794 Add Subbasin NHD+ Table
  src/mmw/apps/modeling/calcs.py
  src/mmw/apps/modeling/urls.py
  src/mmw/apps/modeling/views.py
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/catchmentTable.html
  src/mmw/js/src/modeling/gwlfe/subbasin/views.js
  src/mmw/js/src/modeling/models.js
  src/mmw/js/src/modeling/views.js
Labels: in progress

#2797 Fix Observations Layer tab data loading
  src/mmw/js/src/core/modals/views.js
Labels: in progress

#2798 Subbasin Catchments On Map
  src/mmw/js/src/core/views.js
  src/mmw/js/src/modeling/controllers.js
  src/mmw/js/src/modeling/views.js
  src/mmw/sass/components/_tables.scss
Labels: Sub-basin Modeling, in progress

#2804 Subbasin Weighted BMPs + Misc. Fixes
  src/mmw/apps/modeling/calcs.py
  src/mmw/apps/modeling/tasks.py
  src/mmw/apps/modeling/views.py
  src/mmw/js/src/core/utils.js
  src/mmw/js/src/modeling/gwlfe/subbasin/views.js
  src/mmw/js/src/modeling/models.js
  src/mmw/js/src/modeling/templates/subbasinResultsTabContent.html
  src/mmw/js/src/modeling/views.js
  src/mmw/sass/pages/_model.scss
Labels: in progress

#2806 Show More Sophisticated MapShed Polling
  src/mmw/js/src/core/models.js
  src/mmw/js/src/core/templates/message.html
  src/mmw/js/src/modeling/views.js
Labels: in progress

#2805 Wire Up Subbasin Download CSV Buttons
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/catchmentTable.html
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/huc12TotalsTable.html
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/sourcesTable.html
  src/mmw/js/src/modeling/gwlfe/subbasin/views.js
Labels: in progress
