Repository WikiWatershed/model-my-watershed, pull requests merged in 2018-05, with the labels that each got.

#2803 Give VMs More Resources
  Vagrantfile
  deployment/cfn/application.py
  deployment/default.yml.example
Labels: Monitor, Sub-basin Modeling

#2822 Subbasin: Color Catchments and Streams by SRAT Values
  src/mmw/js/src/core/views.js
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/layerSelector.html
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/result.html
  src/mmw/js/src/modeling/gwlfe/subbasin/views.js
  src/mmw/js/src/modeling/models.js
  src/mmw/js/src/modeling/views.js
  src/mmw/sass/pages/_model.scss
Labels: Sub-basin Modeling, in progress

#2828 Subbasin: Hotspot Info Box
  src/mmw/apps/core/templates/base.html
  src/mmw/apps/user/migrations/0006_userprofile_has_seen_hotspot_info.py
  src/mmw/apps/user/models.py
  src/mmw/apps/user/serializers.py
  src/mmw/apps/user/views.py
  src/mmw/js/src/app.js
  src/mmw/js/src/core/views.js
  src/mmw/js/src/modeling/controllers.js
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/hotspotInfo.html
  src/mmw/js/src/modeling/gwlfe/subbasin/views.js
  src/mmw/js/src/modeling/views.js
  src/mmw/js/src/user/models.js
  src/mmw/sass/components/_mapinfo.scss
  src/mmw/sass/main.scss
  src/mmw/sass/pages/_model.scss
Labels: Sub-basin Modeling, in progress

#2829 Subbasin: Use Continuous Color Ramp for Streams, Catchment Load Rates
  src/mmw/js/src/modeling/gwlfe/subbasin/models.js
  src/mmw/js/src/modeling/models.js
Labels: Sub-basin Modeling

#2831 Update libpq glob to reflect main PostgreSQL repository
  deployment/ansible/group_vars/all
Labels: in progress

#2834 Fix tab padding, move mean flow text
  src/mmw/js/src/modeling/gwlfe/quality/templates/table.html
  src/mmw/sass/pages/_model.scss
Labels: Sub-basin Modeling, in progress

#2835 Subbasin: Fix Failing HUCs
  deployment/ansible/group_vars/all
  src/mmw/apps/modeling/calcs.py
  src/mmw/apps/modeling/mapshed/tasks.py
  src/mmw/apps/modeling/views.py
Labels: Sub-basin Modeling, in progress

#2838 Fix external links for Safari
  src/mmw/apps/water_balance/templates/home_page/index.html
  src/mmw/js/src/account/templates/linkedAccounts.html
  src/mmw/js/src/core/modals/templates/aboutModal.html
  src/mmw/js/src/core/modals/templates/multiShareModal.html
  src/mmw/js/src/core/templates/header.html
  src/mmw/js/src/core/templates/observationPopup.html
  src/mmw/js/src/draw/templates/splash.html
  src/mmw/js/src/modeling/tr55/runoff/templates/table.html
  src/mmw/templates/registration/registration_base.html
Labels: NSF, in progress

#2839 Fix DRB Point Source Listing
  deployment/ansible/group_vars/all
  deployment/ansible/roles/model-my-watershed.celery/tasks/main.yml
  src/mmw/apps/geoprocessing_api/calcs.py
  src/mmw/mmw/settings/base.py
  src/mmw/mmw/settings/data/conus_perimeter.json
  src/mmw/mmw/settings/data/drb_perimeter.json
  src/mmw/mmw/settings/data/drb_simple_perimeter.json
  src/mmw/mmw/settings/data/nhd_region2_simple_perimeter.json
  src/mmw/mmw/settings/data/pa_perimeter.json
  src/mmw/mmw/settings/layer_settings.py
Labels: NSF, in progress

#2842 Add HUC to AoI Name, Fix Catchment Layer Legend Units
  src/mmw/apps/modeling/calcs.py
  src/mmw/apps/modeling/views.py
  src/mmw/js/src/analyze/templates/aoiHeader.html
  src/mmw/js/src/analyze/views.js
  src/mmw/js/src/core/utils.js
  src/mmw/js/src/draw/views.js
  src/mmw/js/src/modeling/templates/modelDetailsDropdown.html
  src/mmw/js/src/modeling/views.js
  src/mmw/js/src/projects/templates/projectRow.html
  src/mmw/js/src/projects/views.js
  src/mmw/mmw/settings/layer_settings.py
  src/mmw/sass/pages/_analyze.scss
  src/mmw/sass/pages/_model.scss
Labels: NSF, in progress

#2845 Jump to Coordinates
  src/mmw/js/src/core/tests.js
  src/mmw/js/src/core/utils.js
  src/mmw/js/src/geocode/models.js
  src/mmw/js/src/geocode/templates/location.html
  src/mmw/js/src/geocode/templates/search.html
  src/mmw/js/src/geocode/views.js
  src/mmw/sass/pages/_search-map.scss
Labels: NSF

#2844 MapShed: Default to 10m for stream length if absent
  src/mmw/apps/modeling/mapshed/tasks.py
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/catchmentTable.html
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/huc12TotalsTable.html
  src/mmw/js/src/modeling/gwlfe/subbasin/templates/sourcesTable.html
Labels: MapShed, NSF

#2840 Monitor: Fix SOAP Fetching
  src/mmw/apps/bigcz/clients/cuahsi/details.py
  src/mmw/js/src/data_catalog/models.js
Labels: Monitor, NSF, in progress

#2843 Monitor: Add Contribute Data Modal
  src/mmw/img/logo-envirodiy.png
  src/mmw/img/logo-hydroshare.png
  src/mmw/img/logo-leafpacknetwork.png
  src/mmw/js/src/data_catalog/templates/contributeModal.html
  src/mmw/js/src/data_catalog/templates/form.html
  src/mmw/js/src/data_catalog/views.js
  src/mmw/sass/components/_buttons.scss
  src/mmw/sass/pages/_data-catalog.scss
Labels: Monitor, NSF, in progress

#2813 Implementing the Water Quality Portal as new Monitor catalog
  src/mmw/apps/bigcz/clients/__init__.py
  src/mmw/apps/bigcz/clients/usgswqp/__init__.py
  src/mmw/apps/bigcz/clients/usgswqp/models.py
  src/mmw/apps/bigcz/clients/usgswqp/search.py
  src/mmw/apps/bigcz/clients/usgswqp/serializers.py
  src/mmw/apps/bigcz/utils.py
  src/mmw/apps/bigcz/views.py
  src/mmw/js/src/data_catalog/models.js
  src/mmw/js/src/data_catalog/templates/resultDetailsUSGSWQP.html
  src/mmw/js/src/data_catalog/templates/searchResultUSGSWQP.html
  src/mmw/js/src/data_catalog/views.js
Labels: Monitor

#2852 Monitor: Pin Pandas to 0.22
  deployment/ansible/roles/model-my-watershed.app/tasks/dev-and-test-dependencies.yml
  src/mmw/requirements/base.txt
Labels: NSF

#2853 Update Contribute modal links
  src/mmw/js/src/data_catalog/templates/contributeModal.html
Labels: NSF, in progress

#2856 Monitor: Add USGS WQP to BiG-CZ
  src/mmw/apps/bigcz/clients/__init__.py
  src/mmw/apps/bigcz/clients/usgswqp/__init__.py
  src/mmw/apps/bigcz/clients/usgswqp/models.py
  src/mmw/apps/bigcz/clients/usgswqp/search.py
  src/mmw/apps/bigcz/clients/usgswqp/serializers.py
  src/mmw/apps/bigcz/utils.py
  src/mmw/apps/bigcz/views.py
  src/mmw/js/src/data_catalog/models.js
  src/mmw/js/src/data_catalog/templates/resultDetailsUSGSWQP.html
  src/mmw/js/src/data_catalog/templates/searchResultUSGSWQP.html
  src/mmw/js/src/data_catalog/views.js
Labels: BigCZ, Monitor, NSF

#2861 Ignore old projects, bad data with no AoI names
  src/mmw/js/src/core/utils.js
Labels: NSF

#2854 MMW Branding Updates
  src/mmw/js/src/draw/settings.js
  src/mmw/js/src/draw/templates/splash.html
  src/mmw/sass/pages/_draw.scss
Labels: NSF
