Repository WikiWatershed/model-my-watershed, pull requests merged in 2018-09, with the labels that each got.

#2948 MapShed BMPs: Conservation Tillage Split, Curve Number
  src/mmw/js/src/core/modificationConfig.json
  src/mmw/js/src/modeling/controls.js
  src/mmw/js/src/modeling/gwlfeModificationConfig.js
Labels: WPF, in progress

#2949 MapShed BMPs: Aggregate GWLF-E Modifications
  src/mmw/js/src/core/utils.js
  src/mmw/js/src/modeling/models.js
  src/mmw/js/src/modeling/views.js
Labels: WPF, in progress

#2957 MapShed BMPs: Update Crop Tillage Practices text
  src/mmw/js/src/core/modificationConfig.json
Labels: MapShed, WPF, in progress

#2963 MapShed Manual Entry: Add Base Settings Modal
  src/mmw/js/src/modeling/controls.js
  src/mmw/js/src/modeling/gwlfe/entry/models.js
  src/mmw/js/src/modeling/gwlfe/entry/templates/modal.html
  src/mmw/js/src/modeling/gwlfe/entry/templates/tabContent.html
  src/mmw/js/src/modeling/gwlfe/entry/templates/tabPanel.html
  src/mmw/js/src/modeling/gwlfe/entry/views.js
  src/mmw/js/src/modeling/models.js
  src/mmw/js/src/modeling/templates/controls/settings.html
  src/mmw/sass/components/_buttons.scss
  src/mmw/sass/components/_modals.scss
Labels: MapShed, WPF, in progress

#2965 Unhide compare view scrollbar
  src/mmw/sass/pages/_compare.scss
Labels: in progress

#2966 MapShed Manual Entry: Add Waste Water Tab
  src/mmw/js/src/modeling/controls.js
  src/mmw/js/src/modeling/gwlfe/entry/calcs.js
  src/mmw/js/src/modeling/gwlfe/entry/models.js
  src/mmw/js/src/modeling/gwlfe/entry/templates/field.html
  src/mmw/js/src/modeling/gwlfe/entry/templates/section.html
  src/mmw/js/src/modeling/gwlfe/entry/templates/tabContent.html
  src/mmw/js/src/modeling/gwlfe/entry/views.js
  src/mmw/js/src/modeling/views.js
  src/mmw/sass/components/_modals.scss
Labels: WPF, in progress

#2968 MapShed Manual Entry: Add Animals Tab
  src/mmw/js/src/modeling/gwlfe/entry/calcs.js
  src/mmw/js/src/modeling/gwlfe/entry/models.js
  src/mmw/js/src/modeling/gwlfe/entry/templates/field.html
  src/mmw/js/src/modeling/gwlfe/entry/views.js
  src/mmw/sass/components/_modals.scss
Labels: MapShed, in progress

#2969 MapShed Manual Entry: Add Other Model Data
  src/mmw/js/src/modeling/gwlfe/entry/views.js
Labels: MapShed, in progress

#2973 Monitor: Tolerate CUAHSI Service Being Unavailable
  deployment/ansible/group_vars/all
  src/mmw/apps/bigcz/clients/cuahsi/search.py
  src/mmw/apps/bigcz/utils.py
  src/mmw/js/src/data_catalog/models.js
Labels: NSF, in progress

#2971 Use staging SRAT url for dev, test, staging
  deployment/ansible/group_vars/development
  deployment/ansible/group_vars/test
Labels: in progress

#2975 Add protected lands overlay to layer selector
  src/mmw/mmw/settings/layer_settings.py
  src/mmw/sass/components/_layerpicker.scss
Labels: in progress

#2977 MapShed Manual Entry: Land Cover Modal
  src/mmw/js/src/core/utils.js
  src/mmw/js/src/modeling/controls.js
  src/mmw/js/src/modeling/gwlfe/entry/models.js
  src/mmw/js/src/modeling/gwlfe/entry/templates/field.html
  src/mmw/js/src/modeling/gwlfe/entry/templates/landCoverModal.html
  src/mmw/js/src/modeling/gwlfe/entry/templates/landCoverTotal.html
  src/mmw/js/src/modeling/gwlfe/entry/views.js
  src/mmw/js/src/modeling/models.js
  src/mmw/js/src/modeling/templates/controls/greenButton.html
  src/mmw/sass/components/_modals.scss
Labels: WPF, in progress

#2980 Add GMS Download button to Scenario Buttons View
  src/mmw/js/src/modeling/templates/scenariosBarButtons.html
  src/mmw/js/src/modeling/views.js
Labels: in progress

#2979 MapShed Manual Entry: Design Review
  src/mmw/js/src/modeling/gwlfe/entry/templates/landCoverTotal.html
  src/mmw/js/src/modeling/gwlfe/entry/views.js
  src/mmw/js/src/modeling/templates/gwlfeScenarioToolbar.html
  src/mmw/js/src/modeling/templates/scenarioMenu.html
  src/mmw/sass/base/_header.scss
  src/mmw/sass/components/_buttons.scss
  src/mmw/sass/components/_dropdowns.scss
  src/mmw/sass/components/_modals.scss
Labels: WPF, in progress
