Repository WikiWatershed/model-my-watershed, pull requests merged in 2018-12, with the labels that each got.

#3036 Unit Conversion: HydroShare Export
  src/mmw/apps/export/tasks.py
  src/mmw/js/src/modeling/mocks.js
  src/mmw/js/src/modeling/models.js
  src/mmw/js/src/modeling/tests.js
Labels: HydroShare Export, Unit Conversion, in progress

#3042 Add Terms of Use, Privacy Policy, Cookie Policy
  src/mmw/js/src/core/modals/templates/aboutModal.html
  src/mmw/js/src/core/modals/templates/cookieModal.html
  src/mmw/js/src/core/modals/templates/privacyModal.html
  src/mmw/js/src/core/modals/templates/tosModal.html
  src/mmw/js/src/core/modals/views.js
  src/mmw/js/src/user/templates/signUpModal.html
  src/mmw/js/src/user/views.js
  src/mmw/sass/components/_modals.scss
Labels: NSF, in progress

#3048 Upgrade Postgis to 2.2
  deployment/ansible/group_vars/all
Labels: in progress

#3051 Privacy Email Update
  src/mmw/js/src/core/modals/templates/privacyModal.html
  src/mmw/js/src/core/modals/templates/tosModal.html
Labels: NSF, in progress

#3053 Replace WikiWatershed domain references with modelmywatershed.org
  deployment/RELEASES.md
  deployment/default.yml.example
  doc/MMW_API_landproperties_demo.ipynb
  doc/MMW_API_watershed_demo.ipynb
  src/mmw/apps/water_balance/templates/home_page/index.html
  src/mmw/js/src/modeling/tr55/runoff/templates/table.html
  src/mmw/mmw/settings/base.py
  src/mmw/mmw/settings/production.py
Labels: in progress

#3057 Unit Conversion: Update Label
  src/mmw/js/src/analyze/tests.js
  src/mmw/js/src/core/units.js
Labels: NSF, Unit Conversion, in progress

#3061 Unit Conversion: Manual Entry Total Calculation
  src/mmw/js/src/modeling/gwlfe/entry/views.js
Labels: NSF, Unit Conversion, bug, in progress

#3062 Unit Conversion: Fix Area Limit
  src/mmw/js/src/core/settings.js
  src/mmw/mmw/settings/base.py
Labels: NSF, Unit Conversion, bug, in progress

#3070 Add HydroShare credentials to Worker VM
  deployment/cfn/worker.py
Labels: in progress
