Repository WikiWatershed/model-my-watershed, pull requests merged in 2018-08, with the labels that each got.

#2898 Add link to download BMP Spreadsheet Tool
  src/mmw/js/src/modeling/gwlfe/quality/templates/table.html
  src/mmw/sass/components/_sidebar.scss
Labels: in progress

#2900 Add hint for entering coordinates
  src/mmw/js/src/geocode/templates/search.html
  src/mmw/js/src/geocode/views.js
Labels: NSF, in progress

#2899 Export BMP Spreadsheet Tool to HydroShare
  src/mmw/apps/export/views.py
Labels: in progress

#2904 Update libpq glob to reflect main PostgreSQL repository
  deployment/ansible/group_vars/all
Labels: in progress

#2906 Upgrade GWLF-E to 1.0.1
  src/mmw/requirements/base.txt
Labels: in progress

#2917 Reorder MultiYear Hydrology Fields
  src/mmw/js/src/modeling/gwlfe/runoff/views.js
  src/mmw/js/src/modeling/models.js
Labels: in progress

#2921 MapShed Compare: Window and Scenario Header Row
  src/mmw/js/src/compare/models.js
  src/mmw/js/src/compare/templates/gwlfeCompareScenarioItem.html
  src/mmw/js/src/compare/templates/tr55CompareScenarioItem.html
  src/mmw/js/src/compare/views.js
  src/mmw/js/src/modeling/views.js
  src/mmw/sass/pages/_compare.scss
Labels: Compare View Revamp, in progress

#2922 Create codepaths for GWLFE Hydrology & Water Quality compare view
  src/mmw/js/src/compare/models.js
  src/mmw/js/src/compare/templates/compareBarChartRow.html
  src/mmw/js/src/compare/views.js
Labels: in progress

#2897 Celerify HydroShare Export
  src/mmw/apps/export/hydroshare.py
  src/mmw/apps/export/migrations/0002_hydroshare_disable_autosync.py
  src/mmw/apps/export/tasks.py
  src/mmw/apps/export/urls.py
  src/mmw/apps/export/views.py
  src/mmw/js/src/core/modals/templates/multiShareModal.html
  src/mmw/js/src/core/modals/views.js
  src/mmw/js/src/modeling/models.js
Labels: HydroShare Export, in progress

#2925 MapShed Compare: Add Dropdown for Attributes
  src/mmw/js/src/compare/models.js
  src/mmw/js/src/compare/templates/compareSelection.html
  src/mmw/js/src/compare/templates/compareWindow2.html
  src/mmw/js/src/compare/views.js
  src/mmw/sass/pages/_compare.scss
Labels: CitSci, Compare View Revamp, in progress

#2923 Create GWLFE Compare View Hydrology line charts
  src/mmw/js/src/compare/models.js
  src/mmw/js/src/compare/templates/compareLineChartRow.html
  src/mmw/js/src/compare/views.js
  src/mmw/js/src/core/chart.js
  src/mmw/sass/pages/_compare.scss
Labels: CitSci, Compare View Revamp, in progress

#2924 Create hydrology tables
  src/mmw/js/src/compare/models.js
  src/mmw/js/src/compare/views.js
  src/mmw/sass/pages/_compare.scss
Labels: CitSci, Compare View Revamp, in progress

#2932 MapShed Compare: Modifications Popover
  src/mmw/js/src/compare/templates/compareDescriptionPopover.html
  src/mmw/js/src/compare/templates/compareModificationsPopover.html
  src/mmw/js/src/compare/views.js
  src/mmw/sass/pages/_compare.scss
Labels: CitSci, Compare View Revamp, in progress

#2933 Add GWLF-E Water Quality Table to Compare View
  src/mmw/js/src/compare/models.js
  src/mmw/js/src/compare/views.js
Labels: CitSci, Compare View Revamp, in progress

#2934 MapShed Compare: Fix Tiny Charts
  src/mmw/js/src/compare/views.js
  src/mmw/js/src/core/chart.js
Labels: CitSci, Compare View Revamp, in progress

#2935 MapShed Compare: Fix Line Chart Issue
  src/mmw/js/shim/nv.d3.js
Labels: CitSci, Compare View Revamp, in progress

#2936 Compare View Revamp: Fix TR-55 Downloads
  src/mmw/js/src/analyze/views.js
  src/mmw/js/src/compare/views.js
  src/mmw/js/src/core/utils.js
  src/mmw/js/src/data_catalog/views.js
Labels: CitSci, Compare View Revamp, in progress

#2940 Clean up compare view code
  src/mmw/js/src/compare/constants.js
  src/mmw/js/src/compare/controllers.js
  src/mmw/js/src/compare/models.js
  src/mmw/js/src/compare/templates/compareModal.html
  src/mmw/js/src/compare/templates/compareWindow.html
  src/mmw/js/src/compare/utils.js
  src/mmw/js/src/compare/views.js
  src/mmw/js/src/routes.js
Labels: in progress

#2943 Adjust GWLFE Compare View Styling
  src/mmw/js/src/compare/templates/compareInputs.html
  src/mmw/js/src/compare/views.js
  src/mmw/sass/pages/_compare.scss
Labels: in progress

#2944 MapShed BMPs: Reclassify Developed Land Categories, and other adjustments
  src/mmw/apps/modeling/mapshed/calcs.py
  src/mmw/js/src/compare/constants.js
  src/mmw/js/src/compare/utils.js
  src/mmw/js/src/compare/views.js
  src/mmw/mmw/settings/gwlfe_settings.py
  src/mmw/requirements/base.txt
Labels: MapShed, in progress

#2946 MapShed BMPs: Adjust Curve Number for Cover Crops
  src/mmw/apps/modeling/calcs.py
  src/mmw/js/src/core/utils.js
  src/mmw/js/src/modeling/gwlfeModificationConfig.js
Labels: MapShed, WPF, in progress
