Repository WikiWatershed/model-my-watershed, pull requests merged in 2019-08, with the labels that each got.

#3134 Upgrade HydroShare Rest Client to 1.3.4
  src/mmw/requirements/base.txt
Labels: NSF

#3129 Update SRAT Catchment API Endpoint
  deployment/ansible/group_vars/development
  deployment/ansible/group_vars/test
Labels: NSF

#3133 Switch API Documentation to DRF-YASG
  src/mmw/apps/geoprocessing_api/schemas.py
  src/mmw/apps/geoprocessing_api/tests.py
  src/mmw/apps/geoprocessing_api/urls.py
  src/mmw/apps/geoprocessing_api/views.py
  src/mmw/apps/modeling/views.py
  src/mmw/mmw/settings/base.py
  src/mmw/mmw/urls.py
  src/mmw/requirements/base.txt
Labels: WPF

#3139 Upgrade back-end dependencies that have security vulnerabilities
  src/mmw/requirements/base.txt
Labels: WPF

#3138 Upgrade Front-end Dependencies
  src/mmw/js/src/analyze/tests.js
  src/mmw/js/src/analyze/views.js
  src/mmw/js/src/core/chart.js
  src/mmw/js/src/core/modals/views.js
  src/mmw/js/src/core/models.js
  src/mmw/js/src/core/settings.js
  src/mmw/js/src/core/tests.js
  src/mmw/js/src/core/utils.js
  src/mmw/js/src/core/views.js
  src/mmw/js/src/core/vizerLayers.js
  src/mmw/js/src/data_catalog/models.js
  src/mmw/js/src/draw/tests.js
  src/mmw/js/src/draw/utils.js
  src/mmw/js/src/draw/views.js
  src/mmw/js/src/modeling/controllers.js
  src/mmw/js/src/modeling/controls.js
  src/mmw/js/src/modeling/gwlfe/runoff/views.js
  src/mmw/js/src/modeling/models.js
  src/mmw/js/src/modeling/tests.js
  src/mmw/npm-shrinkwrap.json
  src/mmw/package.json
  src/tiler/package-lock.json
  src/tiler/package.json
Labels: NSF

#3141 Upgrade cryptography to 2.7
  src/mmw/requirements/base.txt
Labels: WPF

#3143 Upgrade Ulmo to 0.8.5
  src/mmw/apps/bigcz/clients/cuahsi/details.py
  src/mmw/requirements/base.txt
Labels: Monitor, NSF

#3160 Hide Subbasin Catchment Legend When Not In Subbasin Mode
  src/mmw/js/src/modeling/views.js
Labels: WPF
