Repository WikiWatershed/model-my-watershed, pull requests merged in 2019-12, with the labels that each got.

#3208 Upgrade Basemap
  src/mmw/mmw/settings/layer_settings.py
Labels: NSF

#3210 Adjust curve number calculation.
  src/mmw/js/src/modeling/gwlfeModificationConfig.js
Labels: PA DEP

#3207 Create pg_trgm index on boundary_huc* tables to speed up search
  README.md
  scripts/aws/setupdb.sh
Labels: PA DEP

#3213 Upgrade Basemap
  src/mmw/mmw/settings/layer_settings.py
Labels: NSF

#3212 Add P-factor to Other Model Data user configuration in gwlfe.
  src/mmw/js/src/modeling/gwlfe/entry/views.js
Labels: PA DEP

#3205 PA DEP Celery Workflow
  src/mmw/apps/export/tasks.py
  src/mmw/apps/export/views.py
  src/mmw/apps/geoprocessing_api/calcs.py
  src/mmw/apps/geoprocessing_api/tasks.py
  src/mmw/apps/geoprocessing_api/views.py
  src/mmw/apps/modeling/geoprocessing.py
  src/mmw/apps/modeling/mapshed/tasks.py
  src/mmw/mmw/settings/base.py
  src/mmw/requirements/base.txt
Labels: PA DEP

#3216 PA DEP: Add Front-end Button to Download Worksheet
  src/mmw/apps/export/views.py
  src/mmw/js/src/analyze/models.js
  src/mmw/js/src/analyze/templates/resultsWindow.html
  src/mmw/js/src/analyze/templates/worksheetExport.html
  src/mmw/js/src/analyze/views.js
  src/mmw/sass/pages/_analyze.scss
Labels: PA DEP

#3218 Only run ARA Analysis if within ARA Perimeter
  src/mmw/apps/geoprocessing_api/tasks.py
  src/mmw/apps/geoprocessing_api/tests.py
  src/mmw/apps/geoprocessing_api/views.py
  src/mmw/mmw/settings/base.py
  src/mmw/mmw/settings/data/ara_perimeter.json
  src/mmw/mmw/settings/layer_settings.py
Labels: OSI

#3220 Add ARA output to Analyze Land tab
  src/mmw/js/src/analyze/templates/table.html
  src/mmw/js/src/analyze/views.js
  src/mmw/sass/components/_tabs.scss
Labels: OSI

#3221 Switch Climate Analysis to Multioperation
  src/mmw/apps/geoprocessing_api/tasks.py
  src/mmw/apps/geoprocessing_api/tests.py
  src/mmw/apps/geoprocessing_api/views.py
  src/mmw/mmw/settings/base.py
Labels: PA DEP
