Repository WikiWatershed/model-my-watershed, pull requests merged in 2020-01, with the labels that each got.

#3224 Update Default N Efficiencies for Crops, Tillage
  src/mmw/js/src/modeling/gwlfe/entry/views.js
  src/mmw/js/src/modeling/gwlfeModificationConfig.js
  src/mmw/mmw/settings/gwlfe_settings.py
Labels: PA DEP

#3225 Merge pull request #3225 from WikiWatershed/tt/pa-dep-text-edits
  src/mmw/js/src/analyze/templates/worksheetExport.html
  src/mmw/js/src/draw/settings.js
Labels: PA DEP

#3226 Add Analyze Back-end for Protected Lands
  src/mmw/apps/geoprocessing_api/tasks.py
  src/mmw/apps/geoprocessing_api/urls.py
  src/mmw/apps/geoprocessing_api/views.py
  src/mmw/apps/modeling/tasks.py
  src/mmw/js/src/analyze/models.js
  src/mmw/js/src/analyze/views.js
  src/mmw/mmw/settings/base.py
  src/mmw/mmw/settings/layer_classmaps.py
  src/mmw/mmw/settings/layer_settings.py
Labels: OSI

#3232 Make modifications list pop-up scrollable
  src/mmw/sass/base/_header.scss
Labels: NSF

#3228 Add Analyze Front-end for Protected Lands
  README.md
  src/mmw/js/src/analyze/mocks.js
  src/mmw/js/src/analyze/models.js
  src/mmw/js/src/analyze/templates/analyzeResults.html
  src/mmw/js/src/analyze/templates/taskSelector.html
  src/mmw/js/src/analyze/templates/varSelector.html
  src/mmw/js/src/analyze/tests.js
  src/mmw/js/src/analyze/views.js
  src/mmw/js/src/app.js
  src/mmw/js/src/core/models.js
  src/mmw/js/src/modeling/models.js
  src/mmw/mmw/settings/layer_settings.py
  src/mmw/sass/components/_charts.scss
  src/mmw/sass/components/_layerpicker.scss
  src/mmw/sass/utils/_variables.scss
Labels: OSI

#3236 Update PA DEP Excel Spreadsheet to latest
  src/mmw/apps/export/templates/MMW_BMP_Spreadsheet_Tool.xlsx
Labels: PA DEP

#3231 Remove JavaScript test prompt from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PA DEP

#3234 Split Active River Area across NLCD
  src/mmw/js/src/analyze/templates/table.html
  src/mmw/js/src/analyze/templates/tableRow.html
  src/mmw/js/src/analyze/tests.js
  src/mmw/js/src/analyze/views.js
Labels: OSI

#3240 Merge pull request #3240 from WikiWatershed/tt/unit-conversion-missing-conversion
  src/mmw/js/src/compare/views.js
  src/mmw/js/src/modeling/constants.js
  src/mmw/js/src/modeling/gwlfe/entry/views.js
Labels: NSF

#3249 Merge pull request #3249 from WikiWatershed/tt/pa-dep-update-excel-template
  src/mmw/apps/export/templates/MMW_BMP_Spreadsheet_Tool.xlsx
Labels: PA DEP

#3250 Switch back to old basemap temporarily
  src/mmw/mmw/settings/layer_settings.py
Labels: NSF
